"""
LLM-based KPI Generator
Dynamically generates KPIs based on available CSV columns
"""

import json
from typing import List, Dict, Any
from models.gemini import GeminiClient


def llm_generate_kpis(csv_columns: List[str], sample_data: Dict[str, List] = None) -> Dict[str, Dict[str, Any]]:
    """
    Use LLM to generate relevant KPIs based on available CSV columns.
    
    Args:
        csv_columns: List of column names in the CSV
        sample_data: Optional dict with sample values per column
    
    Returns:
        Dict of KPI definitions compatible with existing KPI engine format
    """
    try:
        gemini = GeminiClient()
        
        # Build sample data description
        sample_desc = ""
        if sample_data:
            sample_desc = "\n\nSample Data Preview:\n"
            for col, values in sample_data.items():
                sample_desc += f"  {col}: {values[:3]}\n"
        
        prompt = f"""You are a data analyst. Given these CSV columns, generate relevant business KPIs.

Available Columns:
{json.dumps(csv_columns, indent=2)}
{sample_desc}

Task: Generate 5-10 meaningful KPIs that can be calculated from these columns.

Guidelines:
- Use pandas DataFrame syntax (df['column_name'])
- Include aggregations: sum(), mean(), count(), nunique(), min(), max()
- Create ratios and percentages where meaningful
- Consider business metrics like revenue, transactions, averages, distributions
- Use .groupby() for categorical breakdowns
- NO dependencies (each KPI must be independent)

Return ONLY valid JSON (no markdown, no explanation) in this exact format:
{{
  "KPI Name": {{
    "formula": "df['column'].sum()",
    "columns": ["column"],
    "type": "numeric",
    "description": "Brief description of what this measures",
    "dependencies": []
  }}
}}

Examples:
- Total Revenue: df['purchase_amount_(usd)'].sum()
- Average Transaction: df['purchase_amount_(usd)'].mean()
- Unique Customers: df['customer_reference_id'].nunique()
- Revenue by Product: df.groupby('item_purchased')['purchase_amount_(usd)'].sum().to_dict()
- High Ratings Count: (df['review_rating'] >= 4.0).sum()

Generate KPIs now:"""

        response = gemini.generate_text_only(prompt, temperature=0.4)
        
        # Clean response
        response = response.strip()
        if response.startswith('```'):
            lines = response.split('\n')
            response = '\n'.join([l for l in lines if not l.strip().startswith('```')])
        if response.strip().startswith('json'):
            response = response.strip()[4:]
        
        kpis = json.loads(response)
        
        print(f"\n🤖 LLM Generated {len(kpis)} Custom KPIs:")
        for name in kpis.keys():
            print(f"   • {name}")
        print()
        
        return kpis
        
    except Exception as e:
        print(f"⚠️  LLM KPI generation failed: {e}")
        return {}


def merge_kpis(yaml_kpis: Dict, llm_kpis: Dict, matched_yaml_count: int = 0) -> Dict:
    """
    Merge YAML KPIs with LLM-generated KPIs.
    
    Strategy:
    - Keep all YAML KPIs (standard industry metrics)
    - Add LLM KPIs that don't overlap
    - Prioritize LLM if < 30% YAML KPIs matched
    
    Args:
        yaml_kpis: KPIs from YAML file
        llm_kpis: KPIs generated by LLM
        matched_yaml_count: Number of YAML KPIs that were calculable
    
    Returns:
        Combined KPI dictionary
    """
    combined = yaml_kpis.copy()
    
    # If very few YAML KPIs matched, prioritize LLM
    yaml_match_rate = matched_yaml_count / len(yaml_kpis) if yaml_kpis else 0
    
    print(f"\n📊 KPI Merge Strategy:")
    print(f"   YAML KPIs: {len(yaml_kpis)} (matched: {matched_yaml_count})")
    print(f"   LLM KPIs: {len(llm_kpis)}")
    print(f"   Match rate: {yaml_match_rate:.1%}")
    
    if yaml_match_rate < 0.3:
        print(f"   Strategy: Prioritizing LLM KPIs (low YAML match rate)")
        # Low match rate - use LLM KPIs primarily
        for name, kpi in llm_kpis.items():
            if name not in combined:
                combined[name] = kpi
    else:
        print(f"   Strategy: Adding LLM KPIs as supplements")
        # Good match rate - use LLM as supplements
        for name, kpi in llm_kpis.items():
            if name not in combined:
                combined[name] = kpi
    
    print(f"   ✅ Final: {len(combined)} total KPIs\n")
    return combined

